### ISSUE TITLE
Layers fc1 and fc2

### ISSUE THREAD

**Issue by Ratko92** [richzhang/splitbrainauto#1]
Are fc1 and fc2 convolutional or fully connected layers. If they are in a fact convolutional layers  please tell the number of filters. 

Thanks

**Comment by richzhang** [comment]
They are implemented as convolutional layers, with 4096 filters (https://github.com/richzhang/splitbrainauto/blob/master/models/deploy.prototxt). They are equivalent to fully connected layers, but expressed fully convolutionally (https://people.eecs.berkeley.edu/~jonlong/long_shelhamer_fcn.pdf)
