### ISSUE TITLE
Questions about encoding/decoding and network architecture

### ISSUE THREAD

**Issue by gsdefender** [richzhang/splitbrainauto#2]
Hi,
First of all, thank you for this repository, and please excuse me if the following questions are very basic.
I have started studying the splitbrain network model and reading the paper, but I have not yet understood where the encoding part ends and the decoding part starts in deploy_lab.prototxt. It seems to me that the output of the network gives a feature representation, and not the recreated image I expected to find. Could you please point me in the right direction? 
Also, it seems to me that if you wanted to replicate the architecture described in your paper, you would need to use two networks. Is it correct?
Thank you in advance.

**Comment by richzhang** [comment]
Hi, I stripped away the last layer, and left the rest of the network as a feed-forward feature extractor.

Yes, when I trained it, I trained 2 separate networks. Then I put them together afterwards into a single network.

Thanks!

**Comment by anilbatra2185** [comment]
Hi,
Just to understand, if I have to implement this then following steps need to do
1) L_channel (Input) => Network 1 => ab_channel (output)
2) ab_channel (Input) => Network 2 => L_channel (output)

finally merge both networks along channels for each layers to test different Classification/Detection network comparisons. e.g. Classification network
3) RGB => (Network 1 + Network 2) => fc5 features => classifier

Please let me know If my understanding is correct or not? 
if yes, then I would request you to please let me know how to merge each layer along channel. ( I do agree it is a library/caffe question but if you can help me to with this.)

Thanks

**Comment by ran337287** [comment]
I have the same doubts. And I see the architechture for pre-training only has feature extractor. So during trainning, is there decoder for recontructed images? and 12*12 feature maps could be fed into decoder?

**Comment by richzhang** [comment]
Hi, thanks for the question. The ground truth is heavily downsampled.
