### ISSUE TITLE
Disjoint sub-networks

### ISSUE THREAD

**Issue by william-gx** [richzhang/splitbrainauto#3]
Hi!
I understand the split-brain encoder is formed by concatenating two sub-networks, and thereby the group of each convolution layer should be 2. However, some conv layers in the provided deploy.prototxt only have 1 group, such as conv1 and conv3.
Thanks.

**Comment by richzhang** [comment]
Hi, thanks for the question! If you look at the weights, half of the weights are filled in with zeroes as appropriate. So they are effectively 2 groups in there.
