### ISSUE TITLE
Question Regarding Classification Loss

### ISSUE THREAD

**Issue by SreenivasVRao** [richzhang/splitbrainauto#4]
Hi, I don't quite understand the quantization procedure for classification loss. The L channel is quantized into 100 bins. The ab channels are quantized to the Q=313 values which are in-gamut..? Can you explain the procedure for identifying those values?

I quantize L_labels as np.digitize(image[:,:,0] , np.linspace(0,100,100))
How does it work for ab_labels..?

Secondly, is the regression loss is with respect to these quantized labels?

Apologies if these questions are too trivial.
Thanks! I found your work really fascinating!

**Comment by richzhang** [comment]
Hi, the ab space is quantized into 10x10 bins. Not all values of (a,b) are in gamut however, so we just kept the bins which were. More information, along with a picture of the ab gamut, is found in the top of page 5 here: https://arxiv.org/pdf/1603.08511.pdf . 

Classification loss is used after quantizing. Thanks!
