### ISSUE TITLE
How is performance of Splitbrain with regression loss for semantic segmentation?

### ISSUE THREAD

**Issue by anilbatra2185** [richzhang/splitbrainauto#7]
In Table 4 for semantic segmentation on PASCAL VOC, mentions only for SplitBrain (cl,cl) loss. I am just wondering, did you tried with regression loss pre-trained network?
![table4](https://user-images.githubusercontent.com/7984207/38770962-51796c84-4038-11e8-85f3-2040c1a8499c.png)

**Comment by richzhang** [comment]
Hi, thanks for the question. I had never tried that!
